package vn.edu.hunre.nhom11.carrental.booking.service;
import java.math.BigDecimal;import java.time.*;import java.time.temporal.ChronoUnit;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import vn.edu.hunre.nhom11.carrental.booking.domain.*;import vn.edu.hunre.nhom11.carrental.booking.repository.BookingRepository;import vn.edu.hunre.nhom11.carrental.catalog.service.CarService;import vn.edu.hunre.nhom11.carrental.identity.repository.UserRepository;import vn.edu.hunre.nhom11.carrental.shared.exception.ApiException;
@Service public class BookingService {private final BookingRepository bookings;private final CarService cars;private final UserRepository users;public BookingService(BookingRepository b,CarService c,UserRepository u){bookings=b;cars=c;users=u;}
 @Transactional public Booking create(String email,BookingCommand r){if(r.carId()==null||r.pickupDate()==null||r.returnDate()==null||r.returnDate().isBefore(r.pickupDate()))throw new ApiException(HttpStatus.BAD_REQUEST,"Thời gian thuê không hợp lệ");var car=cars.getForUpdate(r.carId());if(bookings.overlaps(r.carId(),r.pickupDate(),r.returnDate()))throw new ApiException(HttpStatus.CONFLICT,"Xe đã được đặt trong khoảng thời gian này");var user=users.findByEmailIgnoreCase(email).orElseThrow();long days=Math.max(1,ChronoUnit.DAYS.between(r.pickupDate(),r.returnDate()));Booking b=new Booking();b.setCustomer(user);b.setCar(car);b.setPickupDate(r.pickupDate());b.setReturnDate(r.returnDate());b.setPickupLocation(r.pickupLocation());b.setReturnLocation(r.returnLocation());b.setNotes(r.notes());b.setTotalAmount(car.getDailyPrice().multiply(BigDecimal.valueOf(days)));return bookings.save(b);}
 @Transactional(readOnly=true) public Object busyDates(Long carId){cars.get(carId);return bookings.findBusyByCarId(carId).stream().map(b->new BusyRange(b.getPickupDate(),b.getReturnDate())).toList();}
 public Object mine(String email){return bookings.findByCustomerEmailOrderByCreatedAtDesc(email);}public Object all(){return bookings.findAll();}public Booking get(Long id){return bookings.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Không tìm thấy đơn đặt xe"));}
 @Transactional public Booking status(Long id,BookingStatus next){Booking b=get(id);if(b.getStatus()==BookingStatus.COMPLETED||b.getStatus()==BookingStatus.CANCELLED)throw new ApiException(HttpStatus.CONFLICT,"Đơn đã kết thúc, không thể cập nhật");b.setStatus(next);return b;}
 @Transactional public Booking cancel(Long id,String email,boolean admin){Booking b=get(id);if(!admin&&!b.getCustomer().getEmail().equalsIgnoreCase(email))throw new ApiException(HttpStatus.FORBIDDEN,"Bạn không thể hủy đơn này");if(b.getStatus()!=BookingStatus.PENDING&&b.getStatus()!=BookingStatus.APPROVED)throw new ApiException(HttpStatus.CONFLICT,"Trạng thái hiện tại không cho phép hủy");b.setStatus(BookingStatus.CANCELLED);return b;}
 public record BookingCommand(Long carId,LocalDate pickupDate,LocalDate returnDate,String pickupLocation,String returnLocation,String notes){}
 public record BusyRange(LocalDate pickupDate,LocalDate returnDate){}
}
