"use client";
import Link from "next/link";import {useEffect,useState} from "react";import {api,getSession,money} from "@/lib/api";
type Booking={id:number;car:{name:string;imageUrl?:string;location?:string};pickupDate:string;returnDate:string;pickupLocation?:string;returnLocation?:string;totalAmount:number;paidAmount:number;status:string;createdAt:string};
type Profile={name:string;email:string;phone:string;address:string};
type Payment={id:number;amount:number;method:string;status:string;transactionCode:string;createdAt:string};
const statusName:Record<string,string>={PENDING:"Chờ xác nhận",APPROVED:"Đã xác nhận",ACTIVE:"Đang thuê",COMPLETED:"Hoàn tất",CANCELLED:"Đã hủy"};
const methods:Record<string,string>={BANK_TRANSFER:"Chuyển khoản ngân hàng",MOMO:"Ví MoMo",VNPAY:"VNPay",CASH:"Tiền mặt tại quầy"};
export default function Bookings(){const[list,setList]=useState<Booking[]>([]),[profile,setProfile]=useState<Profile|null>(null),[error,setError]=useState(""),[success,setSuccess]=useState(""),[paying,setPaying]=useState<Booking|null>(null),[history,setHistory]=useState<Record<number,Payment[]>>({}),[busy,setBusy]=useState(false);const[form,setForm]=useState({amount:"",method:"BANK_TRANSFER",payerName:"",payerEmail:"",payerPhone:"",billingAddress:"",provider:"Vietcombank",note:""});
 const load=async()=>{try{const[b,p]=await Promise.all([api<Booking[]>("/api/bookings/mine"),api<Profile>("/api/users/me")]);setList(b);setProfile(p);setForm(f=>({...f,payerName:p.name,payerEmail:p.email,payerPhone:p.phone||"",billingAddress:p.address||""}))}catch(e){setError((e as Error).message)}};
 useEffect(()=>{if(!getSession())location.href="/login";else void load()},[]);
 async function cancel(id:number){if(!confirm("Bạn chắc chắn muốn hủy đơn thuê này?"))return;try{setBusy(true);await api(`/api/bookings/${id}`,{method:"DELETE"});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function openPayment(b:Booking){setPaying(b);setSuccess("");setError("");setForm(f=>({...f,amount:String(b.totalAmount-b.paidAmount)}));try{const p=await api<Payment[]>(`/api/payments/${b.id}`);setHistory(h=>({...h,[b.id]:p}))}catch(e){setError((e as Error).message)}}
 async function submitPayment(e:React.FormEvent){e.preventDefault();if(!paying)return;try{setBusy(true);setError("");const p=await api<Payment>("/api/payments",{method:"POST",body:JSON.stringify({...form,bookingId:paying.id,amount:Number(form.amount)})});setSuccess(`Thanh toán thành công. Mã giao dịch: ${p.transactionCode}`);setHistory(h=>({...h,[paying.id]:[...(h[paying.id]||[]),p]}));await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const active=list.filter(b=>!['COMPLETED','CANCELLED'].includes(b.status)).length;
 return <section className="customer-area"><div className="customer-hero"><div><div className="eyebrow">TRUNG TÂM KHÁCH HÀNG</div><h1>Hành trình của bạn</h1><p>Quản lý lịch thuê, theo dõi xác nhận và hoàn tất thanh toán ở một nơi.</p></div><div className="customer-summary"><span><b>{list.length}</b>Tổng đơn</span><span><b>{active}</b>Đang xử lý</span><span><b>{money(list.reduce((s,b)=>s+b.paidAmount,0))}</b>Đã thanh toán</span></div></div>{error&&!paying&&<p className="error">{error}</p>}<div className="customer-layout"><aside className="customer-nav"><Link className="active"href="/bookings">Đơn thuê xe</Link><Link href="/account">Thông tin cá nhân</Link><Link href="/cars">Đặt thêm xe</Link></aside><div className="customer-main"><div className="panel-head"><div><h2>Đơn thuê của tôi</h2><p>{profile?.name}, theo dõi trạng thái từng hành trình tại đây.</p></div></div><div className="booking-cards">{list.map(b=>{const due=b.totalAmount-b.paidAmount;return <article key={b.id}className="booking-card"><div className="booking-card-top"><div><span className={`status ${b.status.toLowerCase()}`}>{statusName[b.status]||b.status}</span><small>ĐƠN #{b.id}</small><h3>{b.car.name}</h3></div><strong>{money(b.totalAmount)}</strong></div><div className="booking-meta"><span><small>NHẬN XE</small><b>{new Date(b.pickupDate).toLocaleDateString("vi-VN")}</b><em>{b.pickupLocation||b.car.location}</em></span><i>→</i><span><small>TRẢ XE</small><b>{new Date(b.returnDate).toLocaleDateString("vi-VN")}</b><em>{b.returnLocation||b.car.location}</em></span></div><div className="payment-progress"><div><span>Đã thanh toán {money(b.paidAmount)}</span><b>{due>0?`Còn ${money(due)}`:"Đã thanh toán đủ"}</b></div><div><i style={{width:`${Math.min(100,b.paidAmount/b.totalAmount*100)}%`}}/></div></div><div className="booking-actions">{due>0&&!['CANCELLED','COMPLETED'].includes(b.status)&&<button className="button small"onClick={()=>openPayment(b)}>Thanh toán ngay</button>}{['PENDING','APPROVED'].includes(b.status)&&<button disabled={busy}className="ghost"onClick={()=>cancel(b.id)}>Hủy đơn</button>}</div></article>})}{!list.length&&<div className="empty-state"><b>Bạn chưa có đơn thuê nào</b><p>Khám phá đội xe và bắt đầu hành trình đầu tiên.</p><Link className="button"href="/cars">Chọn xe ngay</Link></div>}</div></div></div>
 {paying&&<div className="modal-backdrop"onMouseDown={e=>{if(e.target===e.currentTarget)setPaying(null)}}><div className="payment-modal"><button className="modal-close"onClick={()=>setPaying(null)}>×</button><div className="eyebrow">THANH TOÁN ĐƠN #{paying.id}</div><h2>Thông tin thanh toán</h2><div className="payment-order"><span>{paying.car.name}<small>Số tiền còn lại</small></span><b>{money(paying.totalAmount-paying.paidAmount)}</b></div><form onSubmit={submitPayment}><div className="form-grid"><label>Họ và tên người thanh toán<input required value={form.payerName}onChange={e=>setForm({...form,payerName:e.target.value})}/></label><label>Số điện thoại<input required pattern="[0-9+ ]{9,15}"value={form.payerPhone}onChange={e=>setForm({...form,payerPhone:e.target.value})}/></label><label>Email nhận biên lai<input required type="email"value={form.payerEmail}onChange={e=>setForm({...form,payerEmail:e.target.value})}/></label><label>Số tiền thanh toán<input required type="number"min="1000"max={paying.totalAmount-paying.paidAmount}step="1000"value={form.amount}onChange={e=>setForm({...form,amount:e.target.value})}/></label><label className="full">Địa chỉ thanh toán<input required value={form.billingAddress}onChange={e=>setForm({...form,billingAddress:e.target.value})}/></label><label>Phương thức<select value={form.method}onChange={e=>setForm({...form,method:e.target.value,provider:e.target.value==="BANK_TRANSFER"?"Vietcombank":e.target.value})}>{Object.entries(methods).map(([k,v])=><option key={k}value={k}>{v}</option>)}</select></label><label>Ngân hàng / nhà cung cấp<input required value={form.provider}onChange={e=>setForm({...form,provider:e.target.value})}placeholder="VD: Vietcombank"/></label><label className="full">Ghi chú<textarea rows={3}value={form.note}onChange={e=>setForm({...form,note:e.target.value})}placeholder="Nội dung chuyển khoản hoặc yêu cầu xuất hóa đơn..."/></label></div><p className="secure-note">Thông tin được dùng để đối soát và xuất biên nhận. Hệ thống không yêu cầu hoặc lưu số thẻ, CVV.</p>{error&&<p className="error">{error}</p>}{success&&<p className="success">{success}</p>}<button disabled={busy||!!success}className="button payment-submit">{busy?"Đang xử lý...":success?"Đã thanh toán":"Xác nhận thanh toán"}</button></form>{(history[paying.id]||[]).length>0&&<div className="payment-history"><h3>Giao dịch của đơn</h3>{history[paying.id].map(p=><div key={p.id}><span><b>{p.transactionCode}</b><small>{methods[p.method]} · {new Date(p.createdAt).toLocaleString("vi-VN")}</small></span><strong>{money(p.amount)}</strong></div>)}</div>}</div></div>}
 </section>}
